{% set name = "portalocker" %}
{% set version = "2.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 346b2d5695c39dd82d4339bbd7fd0767b5342a997bab8f988c70239ed84c06b7

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                               # [build_platform != target_platform]
    - cross-python_{{ target_platform }}   # [build_platform != target_platform]
  host:
    - python
    - pip
    - pytest-runner
  run:
    - python
    - pywin32  # [win]

test:
  imports:
    - portalocker
  source_files:
    - portalocker_tests
  requires:
    - pytest >=3.4.0
    - pytest-cache >=1.0
    - pytest-cov >=2.5.1
    - pytest-flakes >=2.0.0
    - pytest-pep8 >=1.0.6
  # TODO: how to skip just test_combined ?
  # commands:
  #  - pytest -k "not test_combined" portalocker_tests

about:
  home: https://github.com/WoLpH/portalocker
  license: PSF-2.0
  license_family: PSF
  license_file: LICENSE
  summary: Portalocker is a library to provide an easy API to file locking.
  doc_url: http://portalocker.readthedocs.org
  dev_url: https://github.com/WoLpH/portalocker

extra:
  recipe-maintainers:
    - tyrius02
    - sodre
