{% set name = "portalocker" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 455074565f7da80a9206b821fab72156e456a7e2a4d4cf1650f6bb6a584c396f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                               # [build_platform != target_platform]
    - cross-python_{{ target_platform }}   # [build_platform != target_platform]
  host:
    - python
    - pip
    - pytest-runner
  run:
    - python

test:
  imports:
    - portalocker
  source_files:
    - tests
  requires:
    - pytest >=3.4.0
    - pytest-cache >=1.0
    - pytest-cov >=2.5.1
    - pytest-flakes >=2.0.0
    - pytest-pep8 >=1.0.6
    - pip
  commands:
   - pip check
   - pytest tests/temporary_file_lock.py
   - pytest tests/tests.py

about:
  home: https://github.com/WoLpH/portalocker
  license: PSF-2.0
  license_family: PSF
  license_file: LICENSE
  summary: Portalocker is a library to provide an easy API to file locking.
  doc_url: http://portalocker.readthedocs.org
  dev_url: https://github.com/WoLpH/portalocker

extra:
  recipe-maintainers:
    - tyrius02
    - sodre
